[project]
name = "pollster"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "dotenv>=0.9.9",
    "ruff>=0.14.11",
    "stripe>=14.3.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
